version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - ojo-network/core-devs
    labels:
      - "A:Automerge"
      - "T:Dependencies"
      - "S:backport/v0.1.x"
  - package-ecosystem: gomod
    directory: "/infra/pulumi/testnet"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - ojo-network/core-devs
    labels:
      - "A:Automerge"
      - "T:Dependencies"
