version: 1
build:
  main: ./cmd/ojod
  binary: ojod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 39000000000000uojo
  mnemonic: entry garbage bike poem grunt negative easily annual miss happy license
    blur false fringe program picture inner tape dismiss eagle include quality drill
    master
- name: bob
  coins:
  - 5500000000000uojo
- name: faucet
  coins:
  - 5500000000000uojo
faucet:
  name: faucet
  coins:
  - 5500000000000uojo
  coins_max:
  - 1000000000uojo
  host: 0.0.0.0:4500
  port: 4500
genesis:
  app_state:
    staking:
      params:
        bond_denom: uojo
    oracle:
      params:
        currency_pair_providers:
          - base_denom: USDT
            pair_address: []
            providers:
            - kraken
            - coinbase
            - crypto
            - gate
            quote_denom: USD
          - base_denom: ATOM
            pair_address: []
            providers:
            - okx
            - bitget
            - gate
            quote_denom: USDT
          - base_denom: ATOM
            pair_address: []
            providers:
            - kraken
            quote_denom: USD
  chain_id: ojo-testnet
validators:
- name: alice
  bonded: 33500000000000uojo
