gas_adjustment = 1
provider_timeout = "1000000s"

[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDC"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDC"
threshold = "1.5"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "BTC"
threshold = "2"

[[deviation_thresholds]]
base = "OSMO"
threshold = "2"

[[deviation_thresholds]]
base = "DAI"
threshold = "2"

[[deviation_thresholds]]
base = "stOSMO"
threshold = "2"

[[deviation_thresholds]]
base = "stATOM"
threshold = "2"

[[deviation_thresholds]]
base = "stJUNO"
threshold = "2"

[[deviation_thresholds]]
base = "JUNO"
threshold = "2"

[[deviation_thresholds]]
base = "SCRT"
threshold = "2"

[[deviation_thresholds]]
base = "WETH"
threshold = "2"

[[deviation_thresholds]]
base = "WBTC"
threshold = "2"

[[deviation_thresholds]]
base = "CBETH"
threshold = "2"

[[deviation_thresholds]]
base = "LINK"
threshold = "2"

[[deviation_thresholds]]
base = "RETH"
threshold = "2"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"


[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
  "gate",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "BTC"
providers = [
  "okx",
  "gate",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "BTC"
providers = [
  "coinbase",
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "bitget",
  "gate",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "OSMO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "WETH"
providers = [
  "eth-uniswap"
]
quote = "USDC"

[[currency_pairs]]
base = "WBTC"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "CBETH"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "LINK"
providers = [
  "eth-uniswap"
]
quote = "WETH"

[[currency_pairs]]
base = "RETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "SFRXETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "WSTETH"
providers = [
  "eth-uniswap",
]
quote = "WETH"

[[currency_pairs]]
base = "stATOM"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stOSMO"
providers = [
  "osmosis",
]
quote = "OSMO"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "JUNO"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "JUNO"
providers = [
  "osmosis",
]
quote = "ATOM"

[[currency_pairs]]
base = "stJUNO"
providers = [
  "osmosis",
]
quote = "JUNO"

[[currency_pairs]]
base = "SCRT"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "SCRT"
providers = [
  "mexc",
  "gate"
]
quote = "USDT"

[[currency_pairs]]
base = "INJ"
providers = [
  "gate",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "INJ"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "STINJ"
providers = [
  "astroport",
]
quote = "INJ"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"


[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "ojo-devnet-01"]]
service-name = "price-feeder"
prometheus-retention-time = 100

