name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  install-tparse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Display Go Version
        run: go version
      - uses: actions/cache@v3
        id: cache-go-tparse
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tparse-binary
      - name: Install tparse
        if: steps.cache-go-tparse.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@v0.11.1

  test-unit-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
      - name: Test and Create Coverage Report
        if: env.GIT_DIFF
        run: |
          make test-unit-cover
      - uses: codecov/codecov-action@v3
        if: env.GIT_DIFF
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  build-ojod:
    uses: ./.github/workflows/build.yml

  liveness-test:
    needs: build-ojod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: Cache updated version binary
        id: cache-binaries
        uses: actions/cache@v3
        with:
          path: ./cmd/ojod/ojod
          key: ojod-linux-amd64

      - name: Move new version binary to build folder
        if: steps.cache-binaries.outputs.cache-hit == 'true'
        run: |
          mkdir -p build
          cp ./cmd/ojod/ojod ./build/ojod
          chmod +x ./build/ojod

      - name: Start single node chain
        if: env.GIT_DIFF && steps.cache-binaries.outputs.cache-hit == 'true'
        run: |
          ./contrib/scripts/single-node.sh
      - name: Test Local Network Liveness
        if: env.GIT_DIFF && steps.cache-binaries.outputs.cache-hit == 'true'
        run: |
          sleep 1m
          ./contrib/scripts/test_localnet_liveness.sh 50 5 50 localhost:26657
